### ISSUE TITLE
Windows compatibility?

### ISSUE THREAD

**Issue by hhiru** [Kriegslustig/rss-o-bot#9]
Hello, I'm not quite sure but I think your rss-o-bot is only compatible with linux, am I right? If that's the case, do you plan any version I can run using command prompt on Windows? Thanks for your work!

**Comment by Kriegslustig** [comment]
Sadly I don't have a windows machine to test it on. But I did test it on one at around version `0.8.0` and it worked. If you have the time, it'd be great if you could test it.

**Comment by hhiru** [comment]
Here's a screenshot: https://i.imgur.com/rXOONhE.png

using `DEBUG=rss-o-bot` does not work :/

**Comment by Kriegslustig** [comment]
The `DEBUG=rss-o-bot` sets an environment variable for scope of the command. Can you try setting `DEBUG` to `rss-o-bot` or `"rss-o-bot"` as described [here](http://stackoverflow.com/questions/3803581/setting-a-system-environment-variable-from-a-windows-batch-file#3804979)?

**Comment by hhiru** [comment]
Output said that the value has been saves, but where?

**Comment by hhiru** [comment]
I used

    setx DEBUG "C:\Users\hiru\AppData\Roaming\npm\rss-o-bot.cmd"

**Comment by Kriegslustig** [comment]
Oh, the value should be `"rss-o-bot"`. In the code I'm checking if there's an environment variable called `DEBUG` and its value is `rss-o-bot`. After you've run `setx DEBUG "rss-o-bot"`. You should be able to run `rss-o-bot` again and now see debugging information.

**Comment by hhiru** [comment]
![immagine](https://cloud.githubusercontent.com/assets/11262717/21623724/23acd6d6-d204-11e6-9bdd-3ff434ca9707.png)

nope :/

**Comment by Kriegslustig** [comment]
Could you try running the following two lines in order?

```
setx DEBUG "rss-o-bot"
```
```
rss-o-bot version
```

**Comment by hhiru** [comment]
![immagine](https://cloud.githubusercontent.com/assets/11262717/21624000/4ed4ec08-d205-11e6-9cd3-3455bb228c64.png)

**Comment by Kriegslustig** [comment]
Alright. I think `cmd` probably handles environment variables differently somehow. Could you try the following in PowerShell?

```
set DEBUG "rss-o-bot"
```
```
rss-o-bot version
```

**Comment by hhiru** [comment]
![immagine](https://cloud.githubusercontent.com/assets/11262717/21624119/fc7140dc-d205-11e6-9657-f9dd6de2a241.png)

I misspelled the first command :P

**Comment by Kriegslustig** [comment]
Cool! Have you added a configuration file yet?

**Comment by Kriegslustig** [comment]
Sorry, I really have to work on that error message. It should appear in non-debug mode and contain some more helpful information... 😅 

If you did put a `config.json` file inside of that directory, RSS-o-Bot should find it. But putting your configuration file there is generally a bad idea, since it will probably be deleted with every rss-o-bot update. So creating a directory `C:\Users\hiru\.rss-o-bot` and putting the config file there is a better idea. I'll remove the first `./rss-o-bot/data` option, since it doesn't make much sense 😅 . I did some roughly looked over the code yesterday and found some Unix paths and fixed them. So this version is probably not going to work for windows, but the next one will 🙃. I'll have a device to test the version on this evening.

Thanks again for taking the time to report the issue and iterate with me! 😄

**Comment by Kriegslustig** [comment]
Alright, I was able to fix some issues. The latest release (rss-o-bot@1.0.0-rc.15) contains these fixes. Could you try using this version?

**Comment by hhiru** [comment]
![immagine](https://cloud.githubusercontent.com/assets/11262717/21660663/9e1c32dc-d2d0-11e6-8578-45ee1d85593e.png)

here we go

**Comment by hhiru** [comment]
I know nothing about how node.js works but maybe this can help you with the Windows notifications feature https://github.com/mikaelbr/node-notifier

**Comment by Kriegslustig** [comment]
> [...] maybe this can help you with the Windows notifications [...]
That's actually the framework I'm currently using :)

> I was trying to add filters [...]
It's actually documented [here](https://github.com/Kriegslustig/rss-o-bot/blob/master/docs/man.md#add-url-filter). Please tell me if there's anything unclear. I also added a simple [example](https://github.com/Kriegslustig/rss-o-bot/blob/master/docs/man.md#examples) to the man page.

**Comment by hhiru** [comment]
So.. I'm here again because I have a problem with a URL. It looks like the system does not recognize the url as a feed url because there are parameters at the end of the URL. Example: https://www.nyaa.se/?page=rss&term=Gabriel+DropOut+%5B720p%5D&user=64513

**Comment by Kriegslustig** [comment]
Sorry for the late answer.

> It looks like the system does not recognize the url as a feed url because there are parameters at the end of the URL like &term and &user.

Most shells interpret some characters as syntax. `&` is commonly interpreted as "create a background process from this". To prevent the shell from interpreting these characters you can wrap the string in signle quotes `'`. So try running this instead:

```
rss-o-bot add 'https://www.nyaa.se/?page=rss&term=Gabriel+DropOut+%5B720p%5D&user=64513'
```

> when I try to install rss-o-bot-telegram I have this output:

The `UNMET PEER DEPENDENCY` warning is harmless. It's there because `rss-o-bot-telegram@1.0.0-rc.0` doesn't link to the `rc` version of RSS-o-Bot. So it should still work.

> And I don't know what I have to use in the config file as "telegram-recipient"

The `telegram-recipients` option is documented in the [RSS-o-Bot Telegram README](https://github.com/kriegslustig/rss-o-bot-telegram#telegram-recipients). The documentation might be a little rough though 😅 . Please ask if you have questions about it.

**Comment by hhiru** [comment]
The output for `rss-o-bot poll-telegram` is:

>   rss-o-bot Error: NO_SUCH_COMMAND
  rss-o-bot     at Object.create (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\dist\lib\shared\errors.js:32:15)
  rss-o-bot     at throwO (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\dist\lib\shared\errors.js:27:27)
  rss-o-bot     at MergeMapSubscriber.project (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\dist\cli.js:213:49)
  rss-o-bot     at MergeMapSubscriber._tryNext (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\mergeMap.js:120:27)
  rss-o-bot     at MergeMapSubscriber._next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\mergeMap.js:110:18)
  rss-o-bot     at MergeMapSubscriber.Subscriber.next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:89:18)
  rss-o-bot     at MapSubscriber._next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\map.js:83:26)
  rss-o-bot     at MapSubscriber.Subscriber.next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:89:18)
  rss-o-bot     at MapSubscriber._next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\map.js:83:26)
  rss-o-bot     at MapSubscriber.Subscriber.next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:89:18)
  rss-o-bot     at SwitchMapSubscriber.notifyNext (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\switchMap.js:124:30)
  rss-o-bot     at InnerSubscriber._next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\InnerSubscriber.js:23:21)
  rss-o-bot     at InnerSubscriber.Subscriber.next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:89:18)
  rss-o-bot     at MapSubscriber._next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\map.js:83:26)
  rss-o-bot     at MapSubscriber.Subscriber.next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:89:18)
  rss-o-bot     at MapSubscriber._next (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\map.js:83:26) +0ms
error: No such command.

**Comment by Kriegslustig** [comment]
> The output for rss-o-bot poll-telegram is:

Oh damn. This is now `rss-o-bot-telegram poll`, sorry. I'll update the docs.

> since it looks for the node_modules folder inside of %appdata%\npm\lib instead of %appdata%\npm.

Thanks for the info. What version of NPM are you running (run `npm --version` to get it)? It could be a cross-platform issue. More likely though, this changed from `npm@2.x` to `npm@3.x`. But I'll have to add `%appdata%\npm\node_modules` to the notifier paths anyways. For now though, if you don't want to copy the whole directory, you could instead use the whole path as a `notification-method` in your `.rss-o-bot\config.json`:

```
...
  "notification-methods": [
    "C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot-telegram"
    ...
  ]
...
```

**Comment by hhiru** [comment]
> What version of NPM are you running [...]?

3.10.9

When I enter `rss-o-bot-telegram poll` I have a long list of null that goes endlessly

**Comment by Kriegslustig** [comment]
> When I enter rss-o-bot-telegram poll I have a long list of null that goes endlessly

Yeah, every `null` is a request to the telegram API where the telegram bot doesn't have any messages. I improved the CLI. If you update it (`npm i -g rss-o-bot-telegram`) and run the command again, you should see no output but the command shouldn't exit. Then send a message to your bot. Now you should see a number as the output in the `rss-o-bot-telegram poll` command. That's your Telegram-`recipientId`. Now put that where your telegram username now is.

Also make sure you have the latest version of `rss-o-bot` installed. I made a few pretty important fixes/improvements.

**Comment by hhiru** [comment]
> rss-o-bot test-notification
  rss-o-bot Running command "test-notification" locally. +0ms
  rss-o-bot Passing arguments [] +3ms
  rss-o-bot Passing switches {} +2ms
  rss-o-bot Notifier not in Error: ENOENT: no such file or directory, stat 'C:\Users\hiru\AppData\Roaming\npm\lib\node_modules\telegram' +959ms
  rss-o-bot Notifier not in [object Object] +1ms
  rss-o-bot Continuing with normal operation without notifier telegram +0ms
Failed to load notifier "telegram"
  rss-o-bot EmptyError: no elements in sequence
  rss-o-bot     at EmptyError.Error (native)
  rss-o-bot     at new EmptyError (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\util\EmptyError.js:20:26)
  rss-o-bot     at LastSubscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\last.js:114:31)
  rss-o-bot     at LastSubscriber.Subscriber.complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:114:18)
  rss-o-bot     at SwitchMapSubscriber.Subscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:132:26)
  rss-o-bot     at SwitchMapSubscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\switchMap.js:106:40)
  rss-o-bot     at SwitchMapSubscriber.Subscriber.complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:114:18)
  rss-o-bot     at DoSubscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\do.js:108:30)
  rss-o-bot     at DoSubscriber.Subscriber.complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:114:18)
  rss-o-bot     at MapSubscriber.Subscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:132:26)
  rss-o-bot     at MapSubscriber.Subscriber.complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:114:18)
  rss-o-bot     at FilterSubscriber.Subscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:132:26)
  rss-o-bot     at FilterSubscriber.Subscriber.complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:114:18)
  rss-o-bot     at DefaultIfEmptySubscriber._complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\defaultIfEmpty.js:73:26)
  rss-o-bot     at DefaultIfEmptySubscriber.Subscriber.complete (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\Subscriber.js:114:18)
  rss-o-bot     at OnErrorResumeNextSubscriber.subscribeToNextSource (C:\Users\hiru\AppData\Roaming\npm\node_modules\rss-o-bot\node_modules\rxjs\operator\onErrorResumeNext.js:71:30) +1ms
error: An unknown error occured. Run the command again with the `DEBUG=rss-o-bot` infront to get some more info.

It looks like it is looking for a telegram folder inside node_modules

**Comment by Kriegslustig** [comment]
Alright, and this is running `rss-o-bot@1.0.0-rc.22` and using the config file you posted in the last comment?

**Comment by hhiru** [comment]
this is the config file

> {
  "notification-methods": ["telegram"],
  "telegram-api-token": "api-token",
  "telegram-recipients": ["recipient"]
}

I switched to "telegram" because I made a junction inside the lib folder so I do not have to copy the whole folder but just making a symbolic path inside the lib folder that goes into node_modules

**Comment by Kriegslustig** [comment]
Just to be sure, what's the output of `rss-o-bot -v`?

**Comment by hhiru** [comment]
> C:\Users\hiru>rss-o-bot -v
  rss-o-bot Running command "-v" locally. +0ms
  rss-o-bot Passing arguments [] +3ms
  rss-o-bot Passing switches {} +1ms
RSS-o-Bot Version: 1.0.0-rc.22
